<?php
/* @var Espl\UserModel\Block\Index $block */
$users = $block->getAllUsers();
?>

    <form method="post" action="<?php echo $block->getAddDataPostUrl() ?>">
        <fieldset>
            <div>
                <label for="manufacturer"><?php echo __("Name") ?></label>
                <input type="text" name="name" id="name" />
            </div>
            <div>
                <label for="model"><?php echo __("Description") ?>
                    <input type="text" name="description" id="description" />
            </div>
            <input type="submit" value="<?php echo __("Add Data") ?>" />
        </fieldset>
    </form>
    <hr />
<?php if (count($users) > 0): ?>
    <table border="1">
        <tr>
            <th><?php echo __("ID") ?></th>
            <th><?php echo __("Name") ?></th>
            <th><?php echo __("Description") ?></th>
        </tr>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?php echo $user->getId() ?>
                <td><?php echo $user->getName() ?>
                <td><?php echo $user->getDescription() ?>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <h1><?php echo __("You have no data yet :(") ?></h1>
<?php endif; ?>